### ISSUE TITLE
5.0inch_LCD_Datashet_RGB.pdf missing file

### ISSUE THREAD

**Issue by Atcold** [sipeed/sipeed_wiki#384]
The link in [Drive RGM screen](https://wiki.sipeed.com/hardware/en/tang/Tang-Nano-9K/examples/rgb_screen.html) to
```
https://dl.sipeed.com/fileList/TANG/Nano%209K/6_Chip_Manual/EN/LCD_Datasheet/5.0inch_LCD_Datashet_RGB.pdf
```
is dead. Can someone please fix it?
The correct file name has a space in it: `5.0inch_LCD_Datashet _RGB_.pdf`.

**Comment by wonderfullook** [comment]
Thanks for your feedback
