### ISSUE TITLE
[Gitalk:/hardware/zh/tang/Tang-Nano-Doc/questions.html] 常见问题 - Sipeed Wiki

### ISSUE THREAD

**Issue by wpx-1** [sipeed/sipeed_wiki#393]
https://wiki.sipeed.com/hardware/zh/tang/Tang-Nano-Doc/questions.html 

 None

**Comment by wpx-1** [comment]
使用 ROM的IP核，Place&Route一直卡在70%

**Comment by yangxiaofeng5** [comment]
烧录出现gowin device not found是什么原因呀
