### ISSUE TITLE
M0S BL616 Modul Pinmap & Datasheet (IO24, IO25, IO26 ) -> ( IO20, IO21, IO22 )

### ISSUE THREAD

**Issue by ESP32DE** [sipeed/sipeed_wiki#399]
IO24 IO25 IO26 on M0S Modul #BL616 
should be IO20(FREE), IO21 (TX0), IO22(RX0)
perhabs [not right MOS (BL616) pinmap in #Wiki ](https://wiki.sipeed.com/hardware/en/maixzero/m0s/m0s.html#Pinmap)

![image](https://user-images.githubusercontent.com/16070445/215364730-67d39bbe-c795-4a4c-8a48-c638dd17ed61.png)

and also in the [M0S Datasheet](https://dl.sipeed.com/shareURL/Maix-Zero/M0S/M0S/1_Specification)

**Comment by wonderfullook** [comment]
Updated, thanks
