### ISSUE TITLE
[https://wiki.sipeed.com/hardware/en/maixsense/maixsense-a075v/maixsense-a075v.html#Use-ROS] Does the device support ubuntu 20.04?

### ISSUE THREAD

**Issue by Tacha-S** [sipeed/sipeed_wiki#435]
I can use the device on Ubuntu 22.04.
But, USB network driver can't find in 20.04.
Do you have any solution?

**Comment by wonderfullook** [comment]
> I can use the device on Ubuntu 22.04. But, USB network driver can't find in 20.04. Do you have any solution?

Ues `lsusb` command to check the device first.

**Comment by Tacha-S** [comment]
Ubuntu 22.04 shows the follow device in `lsusb` result.
```bash
Bus 003 Device 020: ID 0525:a4a2 Netchip Technology, Inc. Linux-USB Ethernet/RNDIS Gadget
```

Nothing appears on Ubuntu 20.04.
I have checked dmesgs.

dmesg logs
```bash
[ 5699.346323] usb usb1-port3: Cannot enable. Maybe the USB cable is bad?
[ 5699.346389] usb usb1-port3: attempt power cycle
[ 5700.566181] usb usb1-port3: Cannot enable. Maybe the USB cable is bad?
[ 5701.466526] usb usb1-port3: Cannot enable. Maybe the USB cable is bad?
[ 5701.466592] usb usb1-port3: unable to enumerate USB device
```

**Comment by Tacha-S** [comment]
It could be used by connecting to different USB ports.
