### ISSUE TITLE
[Gitalk:/hardware/zh/lichee/th1520/lpi4a/4_burn_image.html] 烧录镜像 - Sipeed Wiki

### ISSUE THREAD

**Issue by mtuxpe** [sipeed/sipeed_wiki#444]
https://wiki.sipeed.com/hardware/zh/lichee/th1520/lpi4a/4_burn_image.html

**Comment by mtuxpe** [comment]
Driver installation does not work on Windows 11 (English)

**Comment by wonderfullook** [comment]
> Driver installation does not work on Windows 11 (English)

Hi, Disable Windows Driver Signature will solve this trouble.

**Comment by QiaoTuCodes** [comment]
> @mtuxpe
> Driver installation does not work on Windows 11 (English)

don't work on Windows 10, why? because Win11 it's more bugs...it's too young os!

**Comment by SamRun** [comment]
fastboot_driver在哪儿？

**Comment by wonderfullook** [comment]
> fastboot_driver在哪儿？

这里 : https://dl.sipeed.com/shareURL/LICHEE/licheepi4a/07_Tools

**Comment by fishingkids** [comment]
可以简单说下这个启动过程吗U-Boot -> OpenSBI -> Kernel，我看uboot的参数是直接启动的kernel，没明白sbi是如何被加载，又是如何通过sbi引导了kernel的

**Comment by junjiexing** [comment]
请问下在windows上按照文章中的方法刷了LPI4A_BASIC_20240111，但是无法开机，连接HDMI一直是黑屏，只有风扇在转，这个是怎么回事呢？

**Comment by LukeleeTT** [comment]
如何烧写至sd卡

**Comment by flyingcys** [comment]
> @junjiexing
> 请问下在windows上按照文章中的方法刷了LPI4A_BASIC_20240111，但是无法开机，连接HDMI一直是黑屏，只有风扇在转，这个是怎么回事呢？

可以试下我这个老版本的镜像，可以正常开机运行，版本比较老，8G版本可以正常启动
链接: https://pan.baidu.com/s/1Cr2FMvaCIyQzvWvpykSvpA?pwd=pws2 提取码: pws2 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by LizzyLoong** [comment]
大家好，我在fastboot.exe 的路径也匹配那里，那两个.bin文件 是什么，在哪里 呀

**Comment by LukeleeTT** [comment]
为什么在烧录20240602版本的镜像时，出现报错，没办法烧录。 报错显示：Sending sparse 'root' 22/31 (114260 KB)            OKAY [  3.830s]
Writing 'root'                                     OKAY [  2.554s]
Sending sparse 'root' 23/31 (114333 KB)            OKAY [  3.882s]
Writing 'root'                                     OKAY [  2.818s]
Sending sparse 'root' 24/31 (108277 KB)            OKAY [  3.705s]
Writing 'root'                                     FAILED (remote: 'Request would exceed partition size!')
fastboot: error: Command failed
烧录完成
但是同样大小的20240111版本的镜像是没问题的

**Comment by FIFCC** [comment]
> @LukeleeTT
> 为什么在烧录20240602版本的镜像时，出现报错，没办法烧录。 报错显示：Sending sparse 'root' 22/31 (114260 KB)            OKAY [  3.830s]
> Writing 'root'                                     OKAY [  2.554s]
> Sending sparse 'root' 23/31 (114333 KB)            OKAY [  3.882s]
> Writing 'root'                                     OKAY [  2.818s]
> Sending sparse 'root' 24/31 (108277 KB)            OKAY [  3.705s]
> Writing 'root'                                     FAILED (remote: 'Request would exceed partition size!')
> fastboot: error: Command failed
> 烧录完成
> 但是同样大小的20240111版本的镜像是没问题的

有串口的话看看串口信息，或者尝试使用sd卡启动

**Comment by FIFCC** [comment]
> @LukeleeTT
> 如何烧写至sd卡

https://docs.revyos.dev/Installation/licheepi4a/
可以使用软件也可以使用dd命令，下载文件后解压进行烧写
https://mirror.iscas.ac.cn/revyos/extra/images/lpi4a/20240720/sdcard-lpi4a-20240720_171951.img.zst

**Comment by FIFCC** [comment]
> @junjiexing
> 请问下在windows上按照文章中的方法刷了LPI4A_BASIC_20240111，但是无法开机，连接HDMI一直是黑屏，只有风扇在转，这个是怎么回事呢？

可能是刷写的uboot版本不对，如果是早期8+8板卡请刷写 https://mirror.iscas.ac.cn/revyos/extra/images/lpi4a/20240720/ 目录中的8gemmc uboot

**Comment by zjjj31** [comment]
请问openeuler怎么刷到sd卡上启动，全网找不到方法，自己试了用dd命令刷写bin，boot和root三个文件也启动不了。
