### ISSUE TITLE
[Gitalk:/hardware/en/tang/Tang-Nano-Doc/examples.html] Tang Nano Examples - Sipeed Wiki

### ISSUE THREAD

**Issue by laurentiuduca** [sipeed/sipeed_wiki#527]
https://wiki.sipeed.com/hardware/en/tang/Tang-Nano-Doc/examples.html

**Comment by laurentiuduca** [comment]
Hi, 
1. tangnano 20k can not be programmed with openFPGAloader
if it has connected tm1638 (which works with my other fpga producer devkit) like this
stb=73
clk=74
dio=75
gnd=to any gnd pin of tangnano 20k
vcc=to any 5V/3.3V pin of tangnano 20k

2. i want to use the display max7219
and i tried the deadbeef max7219 project (cerkit/max7219TinyFPGA on github)
which works on other fpga producer devkit that i have
but on tang nano 20k does not work.

Can anybody help?

**Comment by wonderfullook** [comment]
> Hi,
> 
> 1. tangnano 20k can not be programmed with openFPGAloader
>    if it has connected tm1638 (which works with my other fpga producer devkit) like this
>    stb=73
>    clk=74
>    dio=75
>    gnd=to any gnd pin of tangnano 20k
>    vcc=to any 5V/3.3V pin of tangnano 20k
> 2. i want to use the display max7219
>    and i tried the deadbeef max7219 project (cerkit/max7219TinyFPGA on github)
>    which works on other fpga producer devkit that i have
>    but on tang nano 20k does not work.
> 
> I use gw_ide in ubuntu
> 
> Can anybody help?

Burn your firmware into flash then connect with your peripherals to see if it this board works. Maybe powersupply not enougt or other unknown reason. And maybe you can use openFPGAloader to detect the board first then try to flash the bitstream file.

**Comment by laurentiuduca** [comment]
> @wonderfullook
> > Hi,
> > 
> > 1. tangnano 20k can not be programmed with openFPGAloader
> >    if it has connected tm1638 (which works with my other fpga producer devkit) like this
> >    stb=73
> >    clk=74
> >    dio=75
> >    gnd=to any gnd pin of tangnano 20k
> >    vcc=to any 5V/3.3V pin of tangnano 20k
> > 2. i want to use the display max7219
> >    and i tried the deadbeef max7219 project (cerkit/max7219TinyFPGA on github)
> >    which works on other fpga producer devkit that i have
> >    but on tang nano 20k does not work.
> > 
> > I use gw_ide in ubuntu
> > 
> > Can anybody help?
> 
> Burn your firmware into flash then connect with your peripherals to see if it this board works. Maybe powersupply not enougt or other unknown reason. And maybe you can use openFPGAloader to detect the board first then try to flash the bitstream file.

Hi, I did; the board is programmed but tm1638 does not show anything, even if i use a project that works on other fpga producers devkits (of course with constraints file changed).

**Comment by wonderfullook** [comment]
> > @wonderfullook
> > > Hi,
> > > 
> > > 1. tangnano 20k can not be programmed with openFPGAloader
> > >    if it has connected tm1638 (which works with my other fpga producer devkit) like this
> > >    stb=73
> > >    clk=74
> > >    dio=75
> > >    gnd=to any gnd pin of tangnano 20k
> > >    vcc=to any 5V/3.3V pin of tangnano 20k
> > > 2. i want to use the display max7219
> > >    and i tried the deadbeef max7219 project (cerkit/max7219TinyFPGA on github)
> > >    which works on other fpga producer devkit that i have
> > >    but on tang nano 20k does not work.
> > > 
> > > I use gw_ide in ubuntu
> > > Can anybody help?
> > 
> > 
> > Burn your firmware into flash then connect with your peripherals to see if it this board works. Maybe powersupply not enougt or other unknown reason. And maybe you can use openFPGAloader to detect the board first then try to flash the bitstream file.
> 
> Hi, I did; the board is programmed but tm1638 does not show anything, even if i use a project that works on other fpga producers devkits (of course with constraints file changed).

So maybe the lack of power supply. Drive tm1638 with other power supply not from tangnano20k, and make sure that all your devices are at the same ground.

**Comment by laurentiuduca** [comment]
> @wonderfullook
> > > @wonderfullook
> > > > Hi,
> > > > 
> > > > 1. tangnano 20k can not be programmed with openFPGAloader
> > > >    if it has connected tm1638 (which works with my other fpga producer devkit) like this
> > > >    stb=73
> > > >    clk=74
> > > >    dio=75
> > > >    gnd=to any gnd pin of tangnano 20k
> > > >    vcc=to any 5V/3.3V pin of tangnano 20k
> > > > 2. i want to use the display max7219
> > > >    and i tried the deadbeef max7219 project (cerkit/max7219TinyFPGA on github)
> > > >    which works on other fpga producer devkit that i have
> > > >    but on tang nano 20k does not work.
> > > > 
> > > > I use gw_ide in ubuntu
> > > > Can anybody help?
> > > 
> > > 
> > > Burn your firmware into flash then connect with your peripherals to see if it this board works. Maybe powersupply not enougt or other unknown reason. And maybe you can use openFPGAloader to detect the board first then try to flash the bitstream file.
> > 
> > Hi, I did; the board is programmed but tm1638 does not show anything, even if i use a project that works on other fpga producers devkits (of course with constraints file changed).
> 
> So maybe the lack of power supply. Drive tm1638 with other power supply not from tangnano20k, and make sure that all your devices are at the same ground.

I did what you've said and tm1638 does not show anything but the red power led (the same as before). I have tried also with another tang nano 20k and the same result.

**Comment by wonderfullook** [comment]
> > @wonderfullook
> > > > @wonderfullook
> > > > > Hi,
> > > > > 
> > > > > 1. tangnano 20k can not be programmed with openFPGAloader
> > > > >    if it has connected tm1638 (which works with my other fpga producer devkit) like this
> > > > >    stb=73
> > > > >    clk=74
> > > > >    dio=75
> > > > >    gnd=to any gnd pin of tangnano 20k
> > > > >    vcc=to any 5V/3.3V pin of tangnano 20k
> > > > > 2. i want to use the display max7219
> > > > >    and i tried the deadbeef max7219 project (cerkit/max7219TinyFPGA on github)
> > > > >    which works on other fpga producer devkit that i have
> > > > >    but on tang nano 20k does not work.
> > > > > 
> > > > > I use gw_ide in ubuntu
> > > > > Can anybody help?
> > > > 
> > > > 
> > > > Burn your firmware into flash then connect with your peripherals to see if it this board works. Maybe powersupply not enougt or other unknown reason. And maybe you can use openFPGAloader to detect the board first then try to flash the bitstream file.
> > > 
> > > 
> > > Hi, I did; the board is programmed but tm1638 does not show anything, even if i use a project that works on other fpga producers devkits (of course with constraints file changed).
> > 
> > 
> > So maybe the lack of power supply. Drive tm1638 with other power supply not from tangnano20k, and make sure that all your devices are at the same ground.
> 
> I did what you've said and tm1638 does not show anything but the red power led (the same as before). I have tried also with another tang nano 20k and the same result.

Make sure your chip choice is GW2AR-LV18QN88C8/I7

**Comment by laurentiuduca** [comment]
i have found the problem - i had to make a clk divider because max7219 connects to tang nano via wires - and we can not use a high frequency for communicating via wires.

**Comment by laurentiuduca** [comment]
thank you

**Comment by NikosCodeA** [comment]
Hello,
I try to use GAO for tang primer 20K, in linux but i get this error:

Can not connect to JTAG server.

I use openFPGALoader for programming and generally have no other issues (except the T9 light is turned on for no reason)

**Comment by NikosCodeA** [comment]
I have figured this out. Using chat gpt i found i had to change the name of one file from libz.so.1 to libz.so.1.bak.But now seems that the trigger i have set does not work...

**Comment by lancej29** [comment]
I tried the "Blink by Cortex-M3" tutorial for the nano 4k and it failed to build the elf file. My first question, is what is the appropriate way to ask for help.
More detail on the failure is that it could not find _exit during link and appears to be using a library within the ARM toolchain that references it:

arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -O2  -g -Wl,-Map,"gmd_tutorial.map" -o "gmd_tutorial.elf"  ./template/gw1ns4c_it.o ./template/main.o  ./lib/StdPeriph_Driver/Sources/gw1ns4c_gpio.o ./lib/StdPeriph_Driver/Sources/gw1ns4c_i2c.o ./lib/StdPeriph_Driver/Sources/gw1ns4c_misc.o ./lib/StdPeriph_Driver/Sources/gw1ns4c_rtc.o ./lib/StdPeriph_Driver/Sources/gw1ns4c_spi.o ./lib/StdPeriph_Driver/Sources/gw1ns4c_syscon.o ./lib/StdPeriph_Driver/Sources/gw1ns4c_timer.o ./lib/StdPeriph_Driver/Sources/gw1ns4c_uart.o ./lib/StdPeriph_Driver/Sources/gw1ns4c_wdog.o  ./lib/CMSIS/DeviceSupport/system/system_gw1ns4c.o  ./lib/CMSIS/DeviceSupport/startup/gmd/startup_gw1ns4c.o  ./lib/CMSIS/CoreSupport/gmd/core_cm3.o   
c:/gmd/toolchain/arm_toolchain/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe: c:/gmd/toolchain/arm_toolchain/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/nofp\libg.a(lib_a-exit.o): in function `exit':
exit.c:(.text.exit+0x16): undefined reference to `_exit'
c:/gmd/toolchain/arm_toolchain/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe: ./lib/CMSIS/DeviceSupport/startup/gmd/startup_gw1ns4c.o: in function `Reset_Handler':
C:\GMD\workspace\gmd_tutorial\Debug/../lib/CMSIS/DeviceSupport/startup/gmd/startup_gw1ns4c.S:151: undefined reference to `__data_start__'
c:/gmd/toolchain/arm_toolchain/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe: C:\GMD\workspace\gmd_tutorial\Debug/../lib/CMSIS/DeviceSupport/startup/gmd/startup_gw1ns4c.S:152: undefined reference to `__data_end__'
collect2.exe: error: ld returned 1 exit status

Any direction would be appreciated.
