### ISSUE TITLE
[Gitalk:/hardware/zh/logic_analyzer/combo8/use_daplink_function.html] 作为DAPLink使用 - Sipeed Wiki

### ISSUE THREAD

**Issue by MR-Hear** [sipeed/sipeed_wiki#531]
https://wiki.sipeed.com/hardware/zh/logic_analyzer/combo8/use_daplink_function.html

**Comment by Rikka1014** [comment]
xpack 0.12.0-2版本的opeocd 下载解压之后，在Clion中“OpenOCD位置”这个选项中添加openocd.exe路径时，打开解压路径中的bin文件夹后根本就不会显示里面有openocd.exe文件，因此无法选择无法添加这个版本的openocd。添加不是xpack版本的openocd时，就可以成功选择到路径中的openocd.exe文件。可是不是xpack版本的openocd又会报错，因此是个死局。目前我的环境是：Windows11 + 正版Clion2024.1.2 + SLogic Combo 8

**Comment by jzz007** [comment]
STM32部分代码进行内存布局优化(执行区域从Flash更换到RAM)，单步执行到这部分代码时，STLink+MDK的表现是无法调试，退出后不影响STLink正常使用，SLogic Combo 8 + MDK的表现是DAP功能无法使用了，需要重新拔插SLogic Combo 8设备之后才能正常使用
