### ISSUE TITLE
[Gitalk:/hardware/en/lichee/th1520/lpi4a/8_application.html] Typical Application - Sipeed Wiki

### ISSUE THREAD

**Issue by AKeen12344** [sipeed/sipeed_wiki#537]
https://wiki.sipeed.com/hardware/en/lichee/th1520/lpi4a/8_application.html

**Comment by AKeen12344** [comment]
Following commands for #7 installation breaks the LiCheePi 4a, current is drawn and heatsink is hot but no fan spin. Emergency TTY says that something about device tree files is broken or missing and the board needs to be reset (i.e. reflashed). Likely old repos somewhere as this is using the latest Sept 12 images.

**Comment by wonderfullook** [comment]
Update your firmware to the latset one

**Comment by AKeen12344** [comment]
Mind enlightening me on what you mean? Going further into what I said, everything I'm using is the LPI4A_20230912.zip available from Mega storage links on Sipeed's wiki. That also includes the uboot, boot, and rootfs files contained within that zip file and writing onto the device as per the wiki.

Far as I'm concerned, all of those files are the only firmware files for the device and the one thing that completely broke the device is the instructions for installing the GCC toolchain.

I also mistakenly listed the wrong part, as it's actually installing the GCC toolchain where my issue is.

**Comment by wu-yue-yu** [comment]
> Following commands for 10 installation of GCC toolchain breaks the LiCheePi 4a, current is drawn and heatsink is hot but no fan spin. Emergency TTY says that something about device tree files is broken or missing and the board needs to be reset (i.e. reflashed). Likely old repos somewhere as this is using the latest Sept 12 images.
> 
> fixed wrong part

Hi, maybe you can just use the command below:
```shell
sudo sed -i '1ideb https://mirror.iscas.ac.cn/revyos/revyos-c910v/ revyos-c910v main' /etc/apt/sources.list
sudo apt update
sudo apt remove build-essential gcc-13 # run this command if there's a preinstall gcc toolchain
sudo apt install -y build-essential
```

**Comment by AKeen12344** [comment]
> > Following commands for 10 installation of GCC toolchain breaks the LiCheePi 4a, current is drawn and heatsink is hot but no fan spin. Emergency TTY says that something about device tree files is broken or missing and the board needs to be reset (i.e. reflashed). Likely old repos somewhere as this is using the latest Sept 12 images.
> > fixed wrong part
> 
> Hi, maybe you can just use the command below:
> 
> ```shell
> sudo sed -i '1ideb https://mirror.iscas.ac.cn/revyos/revyos-c910v/ revyos-c910v main' /etc/apt/sources.list
> sudo apt update
> sudo apt remove build-essential gcc-13 # run this command if there's a preinstall gcc toolchain
> sudo apt install -y build-essential
> ```

It works and the only meaningful difference I can think of that's missing is `sudo apt upgrade -y `

**Comment by jinchenglee** [comment]
I've burned LPI4A_20231214_FULL image to my 16g+128g lichee pi 4a board. However, I found the default gcc and riscv64-linux-gnu-g++ version 13.2.0 doesn't support RISC-V Vector Extension v0.7.1, which is the C910 core has implemented. 

Is this expected? Are the gcc and riscv64-linux-gnu-g++ built with RVV v1.0? Then it seems weired setting and hopefully can be fixed in later releases. I don't bother to try on the board since C910 doesn't support RV v1.0 anyways. 

```
sipeed@lpi4a:~/git_repo/rvv-rollback$ gcc --version
gcc (Debian 13.2.0-4revyos1) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

sipeed@lpi4a:~/git_repo/rvv-rollback$ riscv64-linux-gnu-gcc --version
riscv64-linux-gnu-gcc (Debian 13.2.0-4revyos1) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

sipeed@lpi4a:~/git_repo/rvv-rollback$ riscv64-linux-gnu-g++ -march=rv64gcv0p7  -o bcd2ascii.o ./bcd2ascii-rvv0p7.s 
./bcd2ascii-rvv0p7.s: Assembler messages:
./bcd2ascii-rvv0p7.s:63: Error: unrecognized opcode `vlbu.v v16,(a1)'
./bcd2ascii-rvv0p7.s:94: Error: unrecognized opcode `vsb.v v24,(a0)'
```
