### ISSUE TITLE
[Gitalk:/hardware/zh/tang/tang-primer-20k/primer-20k.html] Tang Primer 20K - Sipeed Wiki

### ISSUE THREAD

**Issue by AlaskaChinese** [sipeed/sipeed_wiki#623]
https://en.wiki.sipeed.com/hardware/zh/tang/tang-primer-20k/primer-20k.html#%E4%BA%A4%E6%B5%81%E6%96%B9%E5%BC%8F

**Comment by AlaskaChinese** [comment]
#3.3. 外设参数对比(<https://en.wiki.sipeed.com/hardware/zh/tang/tang-primer-20k/primer-20k.html#%E5%A4%96%E8%AE%BE%E5%8F%82%E6%95%B0%E5%AF%B9%E6%AF%94>)

**Comment by AlaskaChinese** [comment]
#3.3. 外设参数对比(<https://en.wiki.sipeed.com/hardware/zh/tang/tang-primer-20k/primer-20k.html#%E5%A4%96%E8%AE%BE%E5%8F%82%E6%95%B0%E5%AF%B9%E6%AF%94>)  
（触摸接口	1	4P FPC 连接器）有误，应为6P

**Comment by wonderfullook** [comment]
确实，写错了

**Comment by AlaskaChinese** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
